import type { Metadata } from "next";
import "./globals.css";
import { Playfair_Display, Syne, Lora } from "next/font/google"
import Cursor from "@/components/ui/Cursor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-display",
})

const syne = Syne({
  subsets: ["latin"],
  variable: "--font-ui",
})

const lora = Lora({
  subsets: ["latin"],
  variable: "--font-body",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={`${playfair.variable} ${syne.variable} ${lora.variable}`}
    >
      <body>
        <Cursor />
        {children}
      </body>
    </html>
  )
}
